// Re-export all shared types for convenience
export type {
  User,
  Trip,
  Booking,
  SearchParams,
  SearchResult,
  SearchResponse,
  PerDiemRates,
  DiscountCode,
  LoyaltyAccount,
  LoyaltyValuation,
  Meal,
  DailyMealSummary,
  PerDiemRate,
  ApiResponse,
  SubscriptionTier,
  PerDiemSource,
  TripStatus,
  BookingType,
  MealType,
  DiscountType,
  LoyaltyCategory,
  PerDiemBadge,
} from '@perdiemify/shared';
